<a href="https://colab.research.google.com/github/2303A51770Supreeth/Data-Science/blob/main/Lab-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

scores = np.random.randint(0, 101, size=(4, 4))
print("Test Scores:\n", scores)

row_means = scores.mean(axis=1)
col_means = scores.mean(axis=0)

std_dev = scores.std()
variance = scores.var()

max_value = scores.max()
min_value = scores.min()
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)
print("\nStandard Deviation:", std_dev)
print("Variance:", variance)
print("\nMax Value:", max_value, "at index", max_index)
print("Min Value:", min_value, "at index", min_index)


Test Scores:
 [[54 90 30 63]
 [50 25 47 84]
 [ 4 98 55 11]
 [25 74  3 47]]

Row-wise Means: [59.25 51.5  42.   37.25]
Column-wise Means: [33.25 71.75 33.75 51.25]

Standard Deviation: 28.788018340969565
Variance: 828.75

Max Value: 98 at index (np.int64(2), np.int64(1))
Min Value: 3 at index (np.int64(3), np.int64(2))


In [2]:
import numpy as np

image = np.random.randint(0, 256, size=(3, 3, 3), dtype=np.uint8)
print("RGB Image:\n", image)

red = image[:, :, 0]
green = image[:, :, 1]
blue = image[:, :, 2]

print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)

avg_red = red.mean()
avg_green = green.mean()
avg_blue = blue.mean()

print("\nAverage Red:", avg_red)
print("Average Green:", avg_green)
print("Average Blue:", avg_blue)

brightened = np.clip(image + 50, 0, 255)
print("\nBrightened Image:\n", brightened)



RGB Image:
 [[[194 130   7]
  [131 200 184]
  [152 237 132]]

 [[187 119 181]
  [216 140 227]
  [ 89  95 251]]

 [[ 38 169 157]
  [ 93 130 166]
  [123 171  53]]]

Red Channel:
 [[194 131 152]
 [187 216  89]
 [ 38  93 123]]

Green Channel:
 [[130 200 237]
 [119 140  95]
 [169 130 171]]

Blue Channel:
 [[  7 184 132]
 [181 227 251]
 [157 166  53]]

Average Red: 135.88888888888889
Average Green: 154.55555555555554
Average Blue: 150.88888888888889

Brightened Image:
 [[[244 180  57]
  [181 250 234]
  [202  31 182]]

 [[237 169 231]
  [ 10 190  21]
  [139 145  45]]

 [[ 88 219 207]
  [143 180 216]
  [173 221 103]]]
